import pandas as pd

categories = [
    {"ID": "cs.AI", "Main Category": "Computer Science", "Name": "Artificial Intelligence"},
    {"ID": "cs.AR", "Main Category": "Computer Science", "Name": "Hardware Architecture"},
    {"ID": "cs.CC", "Main Category": "Computer Science", "Name": "Computational Complexity"},
    {"ID": "cs.CE", "Main Category": "Computer Science", "Name": "Computational Engineering, Finance, and Science"},
    {"ID": "cs.CG", "Main Category": "Computer Science", "Name": "Computational Geometry"},
    {"ID": "cs.CL", "Main Category": "Computer Science", "Name": "Computation and Language"},
    {"ID": "cs.CR", "Main Category": "Computer Science", "Name": "Cryptography and Security"},
    {"ID": "cs.CV", "Main Category": "Computer Science", "Name": "Computer Vision and Pattern Recognition"},
    {"ID": "cs.CY", "Main Category": "Computer Science", "Name": "Computers and Society"},
    {"ID": "cs.DB", "Main Category": "Computer Science", "Name": "Databases"},
    {"ID": "cs.DC", "Main Category": "Computer Science", "Name": "Distributed, Parallel, and Cluster Computing"},
    {"ID": "cs.DL", "Main Category": "Computer Science", "Name": "Digital Libraries"},
    {"ID": "cs.DM", "Main Category": "Computer Science", "Name": "Discrete Mathematics"},
    {"ID": "cs.DS", "Main Category": "Computer Science", "Name": "Data Structures and Algorithms"},
    {"ID": "cs.ET", "Main Category": "Computer Science", "Name": "Emerging Technologies"},
    {"ID": "cs.FL", "Main Category": "Computer Science", "Name": "Formal Languages and Automata Theory"},
    {"ID": "cs.GL", "Main Category": "Computer Science", "Name": "General Literature"},
    {"ID": "cs.GR", "Main Category": "Computer Science", "Name": "Graphics"},
    {"ID": "cs.GT", "Main Category": "Computer Science", "Name": "Computer Science and Game Theory"},
    {"ID": "cs.HC", "Main Category": "Computer Science", "Name": "Human-Computer Interaction"},
    {"ID": "cs.IR", "Main Category": "Computer Science", "Name": "Information Retrieval"},
    {"ID": "cs.IT", "Main Category": "Computer Science", "Name": "Information Theory"},
    {"ID": "cs.LG", "Main Category": "Computer Science", "Name": "Machine Learning"},
    {"ID": "cs.LO", "Main Category": "Computer Science", "Name": "Logic in Computer Science"},
    {"ID": "cs.MA", "Main Category": "Computer Science", "Name": "Multiagent Systems"},
    {"ID": "cs.MM", "Main Category": "Computer Science", "Name": "Multimedia"},
    {"ID": "cs.MS", "Main Category": "Computer Science", "Name": "Mathematical Software"},
    {"ID": "cs.NA", "Main Category": "Computer Science", "Name": "Numerical Analysis"},
    {"ID": "cs.NE", "Main Category": "Computer Science", "Name": "Neural and Evolutionary Computing"},
    {"ID": "cs.NI", "Main Category": "Computer Science", "Name": "Networking and Internet Architecture"},
    {"ID": "cs.OH", "Main Category": "Computer Science", "Name": "Other Computer Science"},
    {"ID": "cs.OS", "Main Category": "Computer Science", "Name": "Operating Systems"},
    {"ID": "cs.PF", "Main Category": "Computer Science", "Name": "Performance"},
    {"ID": "cs.PL", "Main Category": "Computer Science", "Name": "Programming Languages"},
    {"ID": "cs.RO", "Main Category": "Computer Science", "Name": "Robotics"},
    {"ID": "cs.SC", "Main Category": "Computer Science", "Name": "Symbolic Computation"},
    {"ID": "cs.SD", "Main Category": "Computer Science", "Name": "Sound"},
    {"ID": "cs.SE", "Main Category": "Computer Science", "Name": "Software Engineering"},
    {"ID": "cs.SI", "Main Category": "Computer Science", "Name": "Social and Information Networks"},
    {"ID": "cs.SY", "Main Category": "Computer Science", "Name": "Systems and Control"},
]

categories_df = pd.DataFrame(categories)
categories_df.to_csv('./Data/categories.csv', index=False)